name: maxima-lsp

dependencies:
  - base
  - lens
  - lens-regex-pcre
  - pcre-light
  - regex-applicative
  - text
  - aeson
  - vector
  - template-haskell
  - lens-aeson
  - aeson-qq
  - bytestring
  - unix
  - containers
  - transformers
  - process
  - lmdb-simple
  - directory
  - split
  - unliftio

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - OverloadedStrings
  - QuasiQuotes
  - RecordPuns
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeOperators
  - ViewPatterns

source-dirs: .


data-files: hoverdb/hoverdb.lmdb*

executables:
  maxima-lsp:
    source-dirs: src
    main:
      main.hs

